### PR TITLE
Update zh_CN.json

### PR DESCRIPTION
**Pull request by SnowCutieOwO**
I FINALLY GOT DONE THIS ANY IT REALLY MAKES ME DIZZY AND ANGRY.

The Author definitely doesn't know if he adds MiniMessage to such a long file - he successfully killed my brain. All color codes need to be turned and keep in pair, which took me for 8 hours and I JUST HAVE TAKEN IT ALL! That's IT! I CANNOT TOLERATE IT ALL.

R.I.P

### CODE REVIEW

**Comment by Clexus** [comment]
[zh_CN.json](https://github.com/WolfyScript/CustomCrafting/files/15335167/zh_CN.json)
updated some missing parts

**Comment by SnowCutieOwO** [comment]
> [zh_CN.json](https://github.com/WolfyScript/CustomCrafting/files/15335167/zh_CN.json) updated some missing parts

直接给我的那个分支推 pull request，我合并以后它会自己显示在这里，你传附件作者懒得弄的

**Comment by YuanYuanOwO** [comment]
amazing work!  
love this :)

**Review by WolfyScript — APPROVED** [review]
Awesome work! 
I definitely feel the conversion from colour codes to MiniMessage… had to do the same for English, and it's so tedious. Thanks for doing the work for this language!

_btw. I know the JSON format is not great... way too many brackets :) Will change that in the future_

**Pull request merged**
